### ISSUE TITLE
Running DEs with multiple treatment groups

### ISSUE THREAD

**Issue by mmzielonka** [linnykos/eSVD2#14]
If I have three treatment groups (i.e. Treatment 1, Treatment 2, and control) and I would like to perform two DEs (Treatment 1 vs. Control and Treatment 2 vs. Control), would you recommend subsetting the data object for each and then running the two DEs separately? Or is there a way to set contrasts such that the full dataset can be used to calculate each gene's overdispersion while running individual DEs? Thank you!

**Comment by linnykos** [comment]
Thank you for your interest!

Currently, eSVD-DE only supports comparing two groups at a time. Hence, I would recommend using your first option (Treatment 1 vs. Control and Treatment 2 vs. Control), and then looking at the similarities in the -log10 p-values as well as the log-fold changes to assess how similar the two treatments are.

We will be releasing a more flushed-out documentation PkgDown website with tutorials in a month, so stay tuned for that! :) (This won't help your current analysis, but will make your usage of our package smoother.)
